version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    ports:
      - '5432:5432'
    networks:
      - app-network

  devopscaseback:
    build: .
    environment:
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASS}@db:5432/${POSTGRES_DB_NAME}
      - DATABASE_NAME=${POSTGRES_DB_NAME}
      - DATABASE_USERNAME=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASS}
      - DATABASE_HOST=db
    depends_on:
      - db
    ports:
      - '3000:3000'
    networks:
      - app-network

  frontend:
    build:
      context: ../devopscasefront # Direciona para o repositório do frontend
    ports:
      - '5173:5173'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
